// Sumas para las cards del dashboard (página inicio)
const cardsData = {
    sumSalesToday: 283547000,
    sumActiveProducts: 11702,
    sumActiveUsers: 19598,
}

// La suma de las ventas diarias de los últimos 7 días
const barChartData = [
    {
        day: "Lun",
        sumInMillions: 150,
    },
    {
        day: "Mar",
        sumInMillions: 89,
    },
    {
        day: "Mié",
        sumInMillions: 159,
    },
    {
        day: "Jue",
        sumInMillions: 175,
    },
    {
        day: "Vie",
        sumInMillions: 157,
    },
    {
        day: "Sáb",
        sumInMillions: 172,
    },
    {
        day: "Dom",
        sumInMillions: 174,
    },
];

// Lista con las ventas de las últimas 24 horas, ordenadas por fecha de compra, de las más recientes a las más antiguas
const recentOrders = [
    {
        _id: 20,
        userFirstname: "Juan",
        userLastname: "Perez",
        totalAmount: 789500,
        orderStatus: "en curso",
        date: "2023-05-13T14:52:54.000Z",
    },
    {
        _id: 19,
        userFirstname: "María",
        userLastname: "López",
        totalAmount: 7525840,
        orderStatus: "en curso",
        date: "2023-05-13T13:08:54.000Z",
    },
    {
        _id: 18,
        userFirstname: "Ángela",
        userLastname: "Rodríguez",
        totalAmount: 5320500,
        orderStatus: "en curso",
        date: "2023-05-13T12:52:54.000Z",
    },
    {
        _id: 17,
        userFirstname: "Carlos",
        userLastname: "Gómez",
        totalAmount: 10547000,
        orderStatus: "en curso",
        date: "2023-05-13T10:08:54.000Z",
    },
    {
        _id: 16,
        userFirstname: "Diego",
        userLastname: "Soria",
        totalAmount: 985500,
        orderStatus: "en curso",
        date: "2023-05-13T08:17:54.000Z",
    },
    {
        _id: 15,
        userFirstname: "Soledad",
        userLastname: "Ramírez",	
        totalAmount: 2684840,
        orderStatus: "en curso",
        date: "2023-05-13T07:24:54.000Z",
    },
    {
        _id: 14,
        userFirstname: "Rodrigo",
        userLastname: "Pérez",
        totalAmount: 4630500,
        orderStatus: "en curso",
        date: "2023-05-13T06:33:54.000Z",
    },
    {
        _id: 13,
        userFirstname: "Romina",
        userLastname: "Alvarado",
        totalAmount: 985000,
        orderStatus: "finalizada",
        date: "2023-05-13T04:45:54.000Z",
    },
    {
        _id: 12,
        userFirstname: "Agustina",
        userLastname: "Alvez",
        totalAmount: 850600,
        orderStatus: "finalizada",
        date: "2023-05-13T02:19:54.000Z",
    },
    {
        _id: 11,
        userFirstname: "Lorenzo",
        userLastname: "Benítez",
        totalAmount: 1780500,
        orderStatus: "finalizada",
        date: "2023-05-13T01:24:54.000Z",
    },
    {
        _id: 10,
        userFirstname: "María",
        userLastname: "López",
        totalAmount: 7525840,
        orderStatus: "finalizada",
        date: "2023-05-13T00:47:54.000Z",
    },
    {
        _id: 9,
        userFirstname: "Ariel",
        userLastname: "Fernández",
        totalAmount: 5320500,
        orderStatus: "finalizada",
        date: "2023-05-12T23:30:54.000Z",
    },
    {
        _id: 8,
        userFirstname: "Gianina",
        userLastname: "Torres",
        totalAmount: 10547000,
        orderStatus: "finalizada",
        date: "2023-05-12T23:08:54.000Z",
    },
    {
        _id: 7,
        userFirstname: "Ezequiel",
        userLastname: "González",
        totalAmount: 985500,
        orderStatus: "finalizada",
        date: "2023-05-12T22:11:54.000Z",
    },
    {   
        _id: 6,
        userFirstname: "Walter",
        userLastname: "Ramírez",
        totalAmount: 2684840,
        orderStatus: "finalizada",
        date: "2023-05-12T20:58:54.000Z",
    },  
    {
        _id: 5,
        userFirstname: "Olivia",
        userLastname: "Quinteros",
        totalAmount: 4630500,
        orderStatus: "finalizada",
        date: "2023-05-12T20:33:54.000Z",
    },
    {
        _id: 4,
        userFirstname: "Romina",
        userLastname: "Salazar",
        totalAmount: 985000,
        orderStatus: "finalizada",
        date: "2023-05-12T20:32:54.000Z",
    },
    {
        _id: 3,
        userFirstname: "Agustina",
        userLastname: "Burgos",
        totalAmount: 850600,
        orderStatus: "finalizada",
        date: "2023-05-12T19:54:54.000Z",
    },
    {
        _id: 2,
        userFirstname: "Fito",
        userLastname: "Páez",
        totalAmount: 1780500,
        orderStatus: "finalizada",
        date: "2023-05-12T19:34:54.000Z",
    },
    {
        _id: 1,
        userFirstname: "Rosa",
        userLastname: "López",
        totalAmount: 7525840,
        orderStatus: "finalizada",
        date: "2023-05-12T19:20:54.000Z",
    }
];

// Lista de usuarios registrados en la plataforma
const users = [
    {
        "_id":"20",
        "firstname":"Rosa",
        "lastname":"López",
        "calification":0,
        "email":"rosaLopez@mail.com",
        "state":true,
        "dateRegister":"2023-05-13T14:51:54.000Z",
        "verified":false,
        "codeverified":972859,
        "recoverycode":null,
        "phone":"112233",
        "password":"1234",
        "address":"callefalsa 123",
        "reviewReceived":[],
        "reviewPost":[],
        "products":[],
        "questions":[],
    },
    {
        "_id":"19",
        "firstname":"Fito",
        "lastname":"Paez",
        "calification":0,
        "email":"fitopaez@mail.com",
        "state":true,
        "dateRegister":"2023-05-13T13:20:54.000Z",
        "verified":true,
        "codeverified":972859,
        "recoverycode":null,
        "phone":"112233",
        "password":"1234",
        "address":"callefalsa 123",
        "reviewReceived":[],
        "reviewPost":[],
        "products":[],
        "questions":[],
    },
    {
        "_id":"18",
        "firstname":"Fito",
        "lastname":"Paez",
        "calification":0,
        "email":"fitopaez@mail.com",
        "state":false,
        "dateRegister":"2023-05-13T12:38:54.000Z",
        "verified":true,
        "codeverified":972859,
        "recoverycode":null,
        "phone":"112233",
        "password":"1234",
        "address":"callefalsa 123",
        "reviewReceived":[],
        "reviewPost":[],
        "products":[],
        "questions":[],
    },
    {
        "_id":"17",
        "firstname":"Fito",
        "lastname":"Paez",
        "calification":0,
        "email":"fitopaez@mail.com",
        "state":true,
        "dateRegister":"2023-05-13T11:49:54.000Z",
        "verified":true,
        "codeverified":972859,
        "recoverycode":null,
        "phone":"112233",
        "password":"1234",
        "address":"callefalsa 123",
        "reviewReceived":[],
        "reviewPost":[],
        "products":[],
        "questions":[],
    },
    {
        "_id":"16",
        "firstname":"Fito",
        "lastname":"Paez",
        "calification":0,
        "email":"fitopaez@mail.com",
        "state":true,
        "dateRegister":"2023-05-13T10:04:54.000Z",
        "verified":true,
        "codeverified":972859,
        "recoverycode":null,
        "phone":"112233",
        "password":"1234",
        "address":"callefalsa 123",
        "reviewReceived":[],
        "reviewPost":[],
        "products":[],
        "questions":[],
    },
    {
        "_id":"15",
        "firstname":"Fito",
        "lastname":"Paez",
        "calification":0,
        "email":"fitopaez@mail.com",
        "state":false,
        "dateRegister":"2023-05-13T09:20:54.000Z",
        "verified":true,
        "codeverified":972859,
        "recoverycode":null,
        "phone":"112233",
        "password":"1234",
        "address":"callefalsa 123",
        "reviewReceived":[],
        "reviewPost":[],
        "products":[],
        "questions":[],
    },
    {
        "_id":"14",
        "firstname":"Fito",
        "lastname":"Paez",
        "calification":0,
        "email":"fitopaez@mail.com",
        "state":true,
        "dateRegister":"2023-05-13T08:27:54.000Z",
        "verified":true,
        "codeverified":972859,
        "recoverycode":null,
        "phone":"112233",
        "password":"1234",
        "address":"callefalsa 123",
        "reviewReceived":[],
        "reviewPost":[],
        "products":[],
        "questions":[],
    },
    {
        "_id":"13",
        "firstname":"Fito",
        "lastname":"Paez",
        "calification":0,
        "email":"fitopaez@mail.com",
        "state":true,
        "dateRegister":"2023-05-13T07:19:54.000Z",
        "verified":true,
        "codeverified":972859,
        "recoverycode":null,
        "phone":"112233",
        "password":"1234",
        "address":"callefalsa 123",
        "reviewReceived":[],
        "reviewPost":[],
        "products":[],
        "questions":[],
    },
    {
        "_id":"12",
        "firstname":"Fito",
        "lastname":"Paez",
        "calification":0,
        "email":"fitopaez@mail.com",
        "state":true,
        "dateRegister":"2023-05-13T06:44:54.000Z",
        "verified":false,
        "codeverified":972859,
        "recoverycode":null,
        "phone":"112233",
        "password":"1234",
        "address":"callefalsa 123",
        "reviewReceived":[],
        "reviewPost":[],
        "products":[],
        "questions":[],
    },
    {
        "_id":"11",
        "firstname":"Fito",
        "lastname":"Paez",
        "calification":0,
        "email":"fitopaez@mail.com",
        "state":true,
        "dateRegister":"2023-05-13T02:30:54.000Z",
        "verified":true,
        "codeverified":972859,
        "recoverycode":null,
        "phone":"112233",
        "password":"1234",
        "address":"callefalsa 123",
        "reviewReceived":[],
        "reviewPost":[],
        "products":[],
        "questions":[],
    },
    {
        "_id":"10",
        "firstname":"Fito",
        "lastname":"Paez",
        "calification":0,
        "email":"fitopaez@mail.com",
        "state":true,
        "dateRegister":"2023-05-13T01:20:54.000Z",
        "verified":true,
        "codeverified":972859,
        "recoverycode":null,
        "phone":"112233",
        "password":"1234",
        "address":"callefalsa 123",
        "reviewReceived":[],
        "reviewPost":[],
        "products":[],
        "questions":[],
    },
    {
        "_id":"9",
        "firstname":"Fito",
        "lastname":"Paez",
        "calification":0,
        "email":"fitopaez@mail.com",
        "state":false,
        "dateRegister":"2023-05-12T23:59:54.000Z",
        "verified":false,
        "codeverified":972859,
        "recoverycode":null,
        "phone":"112233",
        "password":"1234",
        "address":"callefalsa 123",
        "reviewReceived":[],
        "reviewPost":[],
        "products":[],
        "questions":[],
    },
    {
        "_id":"8",
        "firstname":"Fito",
        "lastname":"Paez",
        "calification":0,
        "email":"fitopaez@mail.com",
        "state":true,
        "dateRegister":"2023-05-12T23:44:54.000Z",
        "verified":true,
        "codeverified":972859,
        "recoverycode":null,
        "phone":"112233",
        "password":"1234",
        "address":"callefalsa 123",
        "reviewReceived":[],
        "reviewPost":[],
        "products":[],
        "questions":[],
    },
    {
        "_id":"7",
        "firstname":"Fito",
        "lastname":"Paez",
        "calification":0,
        "email":"fitopaez@mail.com",
        "state":true,
        "dateRegister":"2023-05-12T23:40:54.000Z",
        "verified":true,
        "codeverified":972859,
        "recoverycode":null,
        "phone":"112233",
        "password":"1234",
        "address":"callefalsa 123",
        "reviewReceived":[],
        "reviewPost":[],
        "products":[],
        "questions":[],
    },
    {
        "_id":"6",
        "firstname":"Fito",
        "lastname":"Paez",
        "calification":0,
        "email":"fitopaez@mail.com",
        "state":false,
        "dateRegister":"2023-05-12T22:30:54.000Z",
        "verified":true,
        "codeverified":972859,
        "recoverycode":null,
        "phone":"112233",
        "password":"1234",
        "address":"callefalsa 123",
        "reviewReceived":[],
        "reviewPost":[],
        "products":[],
        "questions":[],
    },
    {
        "_id":"5",
        "firstname":"Fito",
        "lastname":"Paez",
        "calification":0,
        "email":"fitopaez@mail.com",
        "state":true,
        "dateRegister":"2023-05-12T21:51:54.000Z",
        "verified":true,
        "codeverified":972859,
        "recoverycode":null,
        "phone":"112233",
        "password":"1234",
        "address":"callefalsa 123",
        "reviewReceived":[],
        "reviewPost":[],
        "products":[],
        "questions":[],
    },
    {
        "_id":"4",
        "firstname":"Fito",
        "lastname":"Paez",
        "calification":0,
        "email":"fitopaez@mail.com",
        "state":true,
        "dateRegister":"2023-05-12T21:25:54.000Z",
        "verified":false,
        "codeverified":972859,
        "recoverycode":null,
        "phone":"112233",
        "password":"1234",
        "address":"callefalsa 123",
        "reviewReceived":[],
        "reviewPost":[],
        "products":[],
        "questions":[],
    },
    {
        "_id":"3",
        "firstname":"Fito",
        "lastname":"Paez",
        "calification":0,
        "email":"fitopaez@mail.com",
        "state":true,
        "dateRegister":"2023-05-12T21:02:54.000Z",
        "verified":true,
        "codeverified":972859,
        "recoverycode":null,
        "phone":"112233",
        "password":"1234",
        "address":"callefalsa 123",
        "reviewReceived":[],
        "reviewPost":[],
        "products":[],
        "questions":[],
    },
    {
        "_id":"2",
        "firstname":"Roxana",
        "lastname":"Martínez",
        "calification":0,
        "email":"roxanaMartinez@mail.com",
        "state":true,
        "dateRegister":"2023-05-12T20:23:54.000Z",
        "verified":true,
        "codeverified":982859,
        "recoverycode":null,
        "phone":"112233",
        "password":"1234",
        "address":"callefalsa 123",
        "reviewReceived":[],
        "reviewPost":[],
        "products":[],
        "questions":[],
    },
    {
        "_id":"1",
        "firstname":"Fito",
        "lastname":"Paez",
        "calification":0,
        "email":"fitopaez@mail.com",
        "state":true,
        "dateRegister":"2023-05-12T19:20:54.000Z",
        "verified":true,
        "codeverified":972859,
        "recoverycode":null,
        "phone":"112233",
        "password":"1234",
        "address":"callefalsa 123",
        "reviewReceived":[],
        "reviewPost":[],
        "products":[],
        "questions":[],
    },
    
];


module.exports = {
    cardsData,
    barChartData,
    recentOrders,
    users,
};